version: '3'
services:
  drumre-mongodb:
    image: mongo:7.0
    container_name: drumre-mongodb
    ports:
      - 27027:27017
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    volumes:
      - dbdata:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "38081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_URL=mongodb://drumre-mongodb:27017
    depends_on:
      - drumre-mongodb
volumes:
  dbdata:
